import React from 'react'
import Link from 'next/link'
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "คณะพยาบาลศาสตร์ - เกี่ยวกับเรา",
    description: "Generated by create next app",
    keywords: ['nurse', 'cmu', 'next.js']
  };

function AboutPage() {
  return (
    <div>
        <ul style={{display:'flex', listStyle:'none'}}>
            <li style={{padding: '14px 20px',}}><Link href="/" replace>Home</Link></li>
            <li style={{padding: '14px 20px',}}><Link href="/about">About</Link></li>
            <li style={{padding: '14px 20px',}}><Link href="/contact">Contact</Link></li>
        </ul>
        About
    </div>
  )
}

export default AboutPage