import Image from "next/image";
import dogPic from '@/assets/images/dog.jpg'
import Link from "next/link";
import { YouTubeEmbed } from '@next/third-parties/google'
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "คณะพยาบาลศาสตร์ - ติดต่อเรา",
  description: "Generated by create next app",
  keywords: ['nurse', 'cmu', 'next.js']
};

export default function ContactPage() {
  return (
    <main>
      <ul style={{display:'flex', listStyle:'none'}}>
          <li style={{padding: '14px 20px',}}><Link href="/" replace prefetch={false}>Home</Link></li>
          <li style={{padding: '14px 20px',}}><Link href="/about">About</Link></li>
          <li style={{padding: '14px 20px',}}><Link href="/contact">Contact</Link></li>
      </ul>

      hello contact page <br/>
      <Image src={dogPic} alt="dog" priority/>
      <hr/>

      <div>
        <Image src="/next.png" alt="next" width={300} height={300} priority/>
      </div>
      <hr/>

      <div>
        <Image 
            src="https://www.nurse.cmu.ac.th/web/images/research/13192.png" 
            alt="nurse" 
            width={300} 
            height={300} 
            priority>
        </Image>
      </div>
      <hr/>
      <YouTubeEmbed videoid="ogfYd705cRs" height={400} params="controls=0" />
      <hr/>

      <video width="320" height="240" controls preload="none">
        <source src="Google AdSense.mp4" type="video/mp4" />
        <track
          src="/path/to/captions.vtt"
          kind="subtitles"
          srcLang="en"
          label="English"
        />
      </video>
    </main>
  );
}